define([
	//'ah/comp/entities/EntityFactory',

	//'ah/util/form/Upload',
	//'ah/util/form/objects/BonjourServiceObject',
	// 'ah/util/form/objects/VLANGroupObject',
	// 'ah/util/form/objects/ApplicationGroupObject',
	// 'ah/util/dojocover/AHSlider',
	// 'ah/util/TextboxList',
	// 'ah/util/DeviceTag',
	// 'ah/util/form/PasswordLevel',
	// 'ah/util/form/ObscureInput',
	// 'ah/util/Chosen',
	// 'ah/util/Tab',
	// 'ah/util/layout/Menu',
	// 'ah/util/form/objects/IPObject',
	// 'ah/util/form/objects/VLANObject',
	// 'ah/util/form/objects/MACObject',
	// 'ah/util/form/objects/PseProfileObject',
	// 'ah/util/form/objects/CLISupplementObject',
	// 'ah/util/layout/list/ChosenList',
	// 'ah/util/layout/list/SelectList',
	// 'ah/util/layout/list/CustomList',
	// 'ah/util/layout/list/MultiChosenList',
	'ah/util/form/Grid',
	// "ah/util/form/device/DeviceTmpl",
	// 'ah/util/form/device/APTmpl',
	'ah/util/Carousel',
	// 'ah/util/layout/list/SiderList',
	// 'ah/util/layout/list/TagList',
	// 'ah/util/layout/list/TextBoxList',
	'ah/util/form/Dgrid',
	'ah/util/dojocover/Uploader',
	// 'ah/util/layout/list/SelectCardList',
	// 'ah/util/layout/list/SwitchFieldList',
	// 'ah/util/layout/list/GangedList',
	// 'ah/app/controllers/ConfigController',

	"ah/app/GuestInformationList",
	"ah/app/GuestList",
	"ah/app/ModuleManager",
	"ah/app/OperationDialog",
	"ah/app/PromptOperation",
	"ah/app/RegisterComplete",
	"ah/app/RegisterGroup",
	"ah/app/RegisterGuest",
	"ah/app/RegisterGuestComplete",
	"ah/app/RegisterGuestConfirm",
	"ah/app/RegisterHome",
	"ah/app/RegisterInformation",
	"ah/app/RegisterKiosk",
	"ah/app/RegisterType",
	"ah/app/RepeatDialog",
	"ah/app/SelectGuestType"
	],function(){

});
